[package]
name = "aoc-2015"
version = "0.1.0"
authors = ["Dave Allie <dave@daveallie.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-runner = "*"
aoc-runner-derive = "*"
md5 = "0.7.0"
